apiVersion: v1
kind: Service
metadata:
  name: wp_pipe_line_service
spec:
  selector:
    app: wp_pipe_line1
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp_pipe_line1
spec:
  selector:
    matchLabels:
      app: wp_pipe_line1
  replicas: 5
  template:
    metadata:
      labels:
        app: wp_pipe_line1
    spec:
      containers:
      - name: wp_pipe_line1
        image: wp_pipe_line1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
