apiVersion: apps/v1
kind: Deployment
metadata:
  name: WordProcessPipieline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: WordProcessPipieline
  template:
    metadata:
      labels:
        app: WordProcessPipieline
    spec:
      containers:
        - name: wordpress
          image: vanudockerhub/wp_pipeline_1:wp_pipeline_1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: WordProcessPipieline
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: WordProcessPipieline
